apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: udphj4tez-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: udphj4tez-nodejs 
  name: udphj4tez-nodejs
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: udphj4tez-nodejs 
