apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: udphj4tez-nodejs-gitops
  description: This is GitOps manifest for udphj4tez-nodejs   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-selector: rhtap/gitops=udphj4tez-nodejs
    backstage.io/kubernetes-id: udphj4tez-nodejs 
    backstage.io/techdocs-ref: dir:. 
    github.com/project-slug: tnevrlka-rhtap/udphj4tez-nodejs-gitops   
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:udphj4tez-nodejs
